# Generated by Django 5.0.6 on 2024-05-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_description_listing_sold_listing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type_item',
            field=models.CharField(choices=[('REC', 'Records'), ('CLO', 'Clothing'), ('POST', 'Posters'), ('MISC', 'Miscellaneous')], default='MISC', max_length=5),
            preserve_default=False,
        ),
    ]
